package com.boylab.projectstruct.db.tabledao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.boylab.projectstruct.db.table.Table01;
import com.boylab.projectstruct.db.table.Table02;

import com.boylab.projectstruct.db.tabledao.Table01Dao;
import com.boylab.projectstruct.db.tabledao.Table02Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig table01DaoConfig;
    private final DaoConfig table02DaoConfig;

    private final Table01Dao table01Dao;
    private final Table02Dao table02Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        table01DaoConfig = daoConfigMap.get(Table01Dao.class).clone();
        table01DaoConfig.initIdentityScope(type);

        table02DaoConfig = daoConfigMap.get(Table02Dao.class).clone();
        table02DaoConfig.initIdentityScope(type);

        table01Dao = new Table01Dao(table01DaoConfig, this);
        table02Dao = new Table02Dao(table02DaoConfig, this);

        registerDao(Table01.class, table01Dao);
        registerDao(Table02.class, table02Dao);
    }
    
    public void clear() {
        table01DaoConfig.clearIdentityScope();
        table02DaoConfig.clearIdentityScope();
    }

    public Table01Dao getTable01Dao() {
        return table01Dao;
    }

    public Table02Dao getTable02Dao() {
        return table02Dao;
    }

}
